-- MySQL Script generated by MySQL Workbench
-- vie 23 sep 2016 10:24:06 MST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema demo_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema demo_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demo_db` DEFAULT CHARACTER SET utf8 ;
USE `demo_db` ;

-- -----------------------------------------------------
-- Table `demo_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo_db`.`user` ;

CREATE TABLE IF NOT EXISTS `demo_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
